name: build and run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install gtest manually
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest 
        sudo cmake CMakeLists.txt 
        sudo make 
        sudo cp lib/*.a /usr/lib
        sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a 
        sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

    - name: Configure Project
      run: cmake -B build -S .

    - name: Build Project
      run: cmake --build build --target all

    - name: Run Tests
      run: |
        build/tests/perfomance/PerformanceTests 
        build/tests/unit/UnitTests
